[project]
name = "weather-mcp-servers"
version = "0.1.0"
description = "支持天气预报的MCP Server"
readme = "README.md"
authors = [
    { name = "surpassme", email = "surpassmebyme@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
weather-mcp-servers = "weather_mcp_servers:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
